Converting tabs to spaces for brew audit

diff --git a/kubetail b/kubetail
--- a/kubetail
+++ b/kubetail
@@ -81,153 +81,153 @@ examples:
     ${PROGNAME} --tail 1"
 
 if [ $# -eq 0 ]; then
-	echo "$usage"
-	exit 1
+  echo "$usage"
+  exit 1
 fi
 
 if [ "$#" -ne 0 ]; then
-	while [ "$#" -gt 0 ]
-	do
-		case "$1" in
-		-h|--help)
-			echo "$usage"
-			exit 0
-			;;
-		-v|--version)
-			echo "$version"
-			exit 0
-			;;
-		-c|--container)
-			containers+=("$2")
-			;;
-		-e|--regex)
-			regex="regex"
-			;;
-		-t|--context)
-			context="$2"
-			;;
-		-r|--cluster)
-			cluster="--cluster $2"
-			;;
-		-l|--selector)
-			selector=(--selector "$2")
-			pod=""
-			;;
-		-d|--dry-run)
-			dryrun=true
-			;;
-		-p|--previous)
-			previous=true
-			;;
-		-s|--since)
-			if [ -z "$2" ]; then
-				since="${default_since}"
-			else
-				since="$2"
-			fi
-			;;
-		-n|--namespace)
-			if [ -z "$2" ]; then
-				# using namespace from context
-				:
-			else
-				namespace_arg="--namespace $2"
-			fi
-			;;
-		-f|--follow)
-			if [ "$2" = "false" ]; then
-				follow="false"
-			fi
-			;;
-		-b|--line-buffered)
-			if [ "$2" = "true" ]; then
-				line_buffered="| grep - --line-buffered"
-			fi
-			;;
-		-k|--colored-output)
-			if [ -z "$2" ]; then
-				colored_output="${default_colored_output}"
-			else
-				colored_output="$2"
-			fi
-			;;
-		-j|--jq)
-			if [ -z "$2" ]; then
-				jq_selector="${default_jq_selector}"
-			else
-				jq_selector="$2"
-			fi
-			;;
-		-z|--skip-colors)
-			if [ -z "$2" ]; then
-				skip_colors="${default_skip_colors}"
-			else
-				skip_colors="$2"
-			fi
-			;;
-		--timestamps)
-			if [ "$2" = "false" ]; then
-			    timestamps="$1=$2"
-			else
-			    timestamps="$1"
-			fi
-			;;
-		--tail)
-			if [ -z "$2" ]; then
-			    tail="${default_tail}"
-			else
-			    tail="$2"
-			fi
-			;;
-		--)
-			break
-			;;
-		-*)
-			echo "Invalid option '$1'. Use --help to see the valid options" >&2
-			exit 1
-			;;
-		# an option argument, continue
-		*)  ;;
-		esac
-		shift
-	done
+  while [ "$#" -gt 0 ]
+  do
+    case "$1" in
+    -h|--help)
+      echo "$usage"
+      exit 0
+      ;;
+    -v|--version)
+      echo "$version"
+      exit 0
+      ;;
+    -c|--container)
+      containers+=("$2")
+      ;;
+    -e|--regex)
+      regex="regex"
+      ;;
+    -t|--context)
+      context="$2"
+      ;;
+    -r|--cluster)
+      cluster="--cluster $2"
+      ;;
+    -l|--selector)
+      selector=(--selector "$2")
+      pod=""
+      ;;
+    -d|--dry-run)
+      dryrun=true
+      ;;
+    -p|--previous)
+      previous=true
+      ;;
+    -s|--since)
+      if [ -z "$2" ]; then
+        since="${default_since}"
+      else
+        since="$2"
+      fi
+      ;;
+    -n|--namespace)
+      if [ -z "$2" ]; then
+        # using namespace from context
+        :
+      else
+        namespace_arg="--namespace $2"
+      fi
+      ;;
+    -f|--follow)
+      if [ "$2" = "false" ]; then
+        follow="false"
+      fi
+      ;;
+    -b|--line-buffered)
+      if [ "$2" = "true" ]; then
+        line_buffered="| grep - --line-buffered"
+      fi
+      ;;
+    -k|--colored-output)
+      if [ -z "$2" ]; then
+        colored_output="${default_colored_output}"
+      else
+        colored_output="$2"
+      fi
+      ;;
+    -j|--jq)
+      if [ -z "$2" ]; then
+        jq_selector="${default_jq_selector}"
+      else
+        jq_selector="$2"
+      fi
+      ;;
+    -z|--skip-colors)
+      if [ -z "$2" ]; then
+        skip_colors="${default_skip_colors}"
+      else
+        skip_colors="$2"
+      fi
+      ;;
+    --timestamps)
+      if [ "$2" = "false" ]; then
+          timestamps="$1=$2"
+      else
+          timestamps="$1"
+      fi
+      ;;
+    --tail)
+      if [ -z "$2" ]; then
+          tail="${default_tail}"
+      else
+          tail="$2"
+      fi
+      ;;
+    --)
+      break
+      ;;
+    -*)
+      echo "Invalid option '$1'. Use --help to see the valid options" >&2
+      exit 1
+      ;;
+    # an option argument, continue
+    *)  ;;
+    esac
+    shift
+  done
 fi
 
 # Join function that supports a multi-character separator (copied from http://stackoverflow.com/a/23673883/398441)
 function join() {
-	# $1 is return variable name
-	# $2 is sep
-	# $3... are the elements to join
-	local retname=$1 sep=$2 ret=$3
-	shift 3 || shift $(($#))
-	printf -v "$retname" "%s" "$ret${@/#/$sep}"
+  # $1 is return variable name
+  # $2 is sep
+  # $3... are the elements to join
+  local retname=$1 sep=$2 ret=$3
+  shift 3 || shift $(($#))
+  printf -v "$retname" "%s" "$ret${@/#/$sep}"
 }
 
 function is_regex_matching() {
-	"${regex}" == 'regex'
+  "${regex}" == 'regex'
 }
 
 # Check if pod query contains a comma and we've not specified "regex" explicitly,
 # if so we convert the pod query string into a regex that matches all pods seperated by the comma
 if [[ "${pod}" = *","* ]] && [ ! "${regex}" == 'regex' ]; then
 
-	# Split the supplied query string (in variable pod) by comma into an array named "pods_to_match"
-	IFS=',' read -r -a pods_to_match <<< "${pod}"
+  # Split the supplied query string (in variable pod) by comma into an array named "pods_to_match"
+  IFS=',' read -r -a pods_to_match <<< "${pod}"
 
-	# Join all pod names into a string with ".*|.*" as delimiter
-	join pod ".*|.*" "${pods_to_match[@]}"
+  # Join all pod names into a string with ".*|.*" as delimiter
+  join pod ".*|.*" "${pods_to_match[@]}"
 
-	# Prepend and initial ".*" and and append the last ".*"
-	pod=".*${pod}.*"
+  # Prepend and initial ".*" and and append the last ".*"
+  pod=".*${pod}.*"
 
-	# Force the use of regex matching
-	regex='regex'
+  # Force the use of regex matching
+  regex='regex'
 fi
 
 grep_matcher=''
 if [ "${regex}" == 'regex' ]; then
-	echo "Using regex '${pod}' to match pods"
-	grep_matcher='-E'
+  echo "Using regex '${pod}' to match pods"
+  grep_matcher='-E'
 fi
 
 # Get all pods matching the input and put them in an array. If no input then all pods are matched.
@@ -235,8 +235,8 @@ matching_pods=(`${KUBECTL_BIN} get pods ${context:+--context=${context}} "${sele
 matching_pods_size=${#matching_pods[@]}
 
 if [ ${matching_pods_size} -eq 0 ]; then
-	echo "No pod exists that matches ${pod}"
-	exit 1
+  echo "No pod exists that matches ${pod}"
+  exit 1
 fi
 
 color_end=$(tput sgr0)
@@ -248,18 +248,18 @@ i=0
 color_index=0
 
 function next_col {
-	potential_col=$(($1+1))
-	[[ $skip_colors =~ (^|,)$potential_col($|,) ]] && echo `next_col $potential_col` || echo $potential_col
+  potential_col=$(($1+1))
+  [[ $skip_colors =~ (^|,)$potential_col($|,) ]] && echo `next_col $potential_col` || echo $potential_col
 }
 
 # Allows for more colors, this is useful if one tails a lot pods
 if [ ${colored_output} != "false" ]; then
-	export TERM=xterm-256color
+  export TERM=xterm-256color
 fi
 
 # Function that kills all kubectl processes that are started by kubetail in the background
 function kill_kubectl_processes {
-	kill 0
+  kill 0
 }
 
 # Invoke the "kill_kubectl_processes" function when the script is stopped (including ctrl+c)
@@ -272,50 +272,50 @@ all_pods_containers=$(echo -e `${KUBECTL_BIN} get pods ${namespace_arg} ${contex
 
 
 for pod in ${matching_pods[@]}; do
-	if [ ${#containers[@]} -eq 0 ]; then
-		pod_containers=($(echo -e "$all_pods_containers" | grep $pod | cut -d ' ' -f2- | xargs -n1))
-	else
-		pod_containers=("${containers[@]}")
-	fi
+  if [ ${#containers[@]} -eq 0 ]; then
+    pod_containers=($(echo -e "$all_pods_containers" | grep $pod | cut -d ' ' -f2- | xargs -n1))
+  else
+    pod_containers=("${containers[@]}")
+  fi
 
-	for container in ${pod_containers[@]}; do
-		if [ ${colored_output} == "false" ] || [ ${matching_pods_size} -eq 1 -a ${#pod_containers[@]} -eq 1 ]; then
-			color_start=$(tput sgr0)
-		else
-			color_index=`next_col $color_index`
-			color_start=$(tput setaf $color_index)
-		fi
+  for container in ${pod_containers[@]}; do
+    if [ ${colored_output} == "false" ] || [ ${matching_pods_size} -eq 1 -a ${#pod_containers[@]} -eq 1 ]; then
+      color_start=$(tput sgr0)
+    else
+      color_index=`next_col $color_index`
+      color_start=$(tput setaf $color_index)
+    fi
 
-		if [ ${#pod_containers[@]} -eq 1 ]; then
-			display_name="${pod}"
-		else
-			display_name="${pod} ${container}"
-		fi
-		display_names_preview+=("${color_start}${display_name}${color_end}")
+    if [ ${#pod_containers[@]} -eq 1 ]; then
+      display_name="${pod}"
+    else
+      display_name="${pod} ${container}"
+    fi
+    display_names_preview+=("${color_start}${display_name}${color_end}")
 
-		if [ ${colored_output} == "pod" ]; then
-			colored_line="${color_start}[${display_name}]${color_end} \$REPLY"
-		else
-			colored_line="${color_start}[${display_name}] \$REPLY ${color_end}"
-		fi
+    if [ ${colored_output} == "pod" ]; then
+      colored_line="${color_start}[${display_name}]${color_end} \$REPLY"
+    else
+      colored_line="${color_start}[${display_name}] \$REPLY ${color_end}"
+    fi
 
-		kubectl_cmd="${KUBECTL_BIN} ${context:+--context=${context}} logs ${pod} ${container} -f=${follow} --previous=${previous} --since=${since} --tail=${tail} ${namespace_arg} ${cluster}"
-		colorify_lines_cmd="while read -r; do echo \"$colored_line\" | tail -n +1; done"
-		if [ "z" == "z$jq_selector" ]; then
-			logs_commands+=("${kubectl_cmd} ${timestamps} | ${colorify_lines_cmd}");
-		else
-			logs_commands+=("${kubectl_cmd} | jq --unbuffered -r -R --stream '. as \$line | try (fromjson | $jq_selector) catch \$line' | ${colorify_lines_cmd}");
-		fi
+    kubectl_cmd="${KUBECTL_BIN} ${context:+--context=${context}} logs ${pod} ${container} -f=${follow} --previous=${previous} --since=${since} --tail=${tail} ${namespace_arg} ${cluster}"
+    colorify_lines_cmd="while read -r; do echo \"$colored_line\" | tail -n +1; done"
+    if [ "z" == "z$jq_selector" ]; then
+      logs_commands+=("${kubectl_cmd} ${timestamps} | ${colorify_lines_cmd}");
+    else
+      logs_commands+=("${kubectl_cmd} | jq --unbuffered -r -R --stream '. as \$line | try (fromjson | $jq_selector) catch \$line' | ${colorify_lines_cmd}");
+    fi
 
-		# There are only 11 usable colors
-		i=$(( ($i+1)%13 ))
-	done
+    # There are only 11 usable colors
+    i=$(( ($i+1)%13 ))
+  done
 done
 
 # Preview pod colors
 echo "Will tail ${#display_names_preview[@]} logs..."
 for preview in "${display_names_preview[@]}"; do
-	echo "$preview"
+  echo "$preview"
 done
 
 if [[ ${dryrun} == true ]];
@@ -332,6 +332,6 @@ join command_to_tail " & " "${logs_commands[@]}"
 tail_follow_command="-f"
 if [[ ${follow} == false ]];
 then
-	tail_follow_command=""
+  tail_follow_command=""
 fi
 tail ${tail_follow_command} -n +1 <( eval "${command_to_tail}" ) $line_buffered
